### ISSUE TITLE
Timeline screen/ Commits tab - duplicated commits

### ISSUE THREAD

**Issue by wokeGit** [argoproj/argo#101]
Go to Timeline/Commits scroll down, there are duplicated commits. 
![screen shot 2017-08-30 at 13 45 57](https://user-images.githubusercontent.com/13086525/29870906-0fe0caee-8d8a-11e7-8d5e-fa93543ab5b3.png)
![screen shot 2017-08-30 at 13 46 16](https://user-images.githubusercontent.com/13086525/29870907-11127066-8d8a-11e7-85b0-48f7e4451e6e.png)
![screen shot 2017-08-30 at 13 46 33](https://user-images.githubusercontent.com/13086525/29870910-1381c25c-8d8a-11e7-9ab3-dd7af3798102.png)

**Comment by jessesuen** [comment]
This is actually by design. Notice that the repos of all the commits are actually different. This is a consequence of our unfortunate decision to display commits from multiple repos on a single view. 

Showing a consolidated view of commits is not only unscalable from a backend perspective, but IMO, confusing from a user perspective (as demonstrated by this bug). I would have preferred that a single repository be selected, as a prerequisite to seeing commits.

**Comment by wokeGit** [comment]
Ok I see it. 
We still have a bug at the UI, generally we are able to expand selected commit panel. 

Expected result:

The assumption is to have only one panel expanded at a time. 

Actual result:

All the commits with the same revision are expanded if click any of them.

**Comment by wokeGit** [comment]
As it is still issue but at the ui side I created separate bug for that (https://github.com/argoproj/argo/issues/119) and close this one.
