### ISSUE TITLE
Workflow tree is not usable if workflow has a lot of nodes

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#1088]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

**What happened**: Workflow tree should be improved to render large workflows. Attached screenshot demonstrates issue:

<img width="1433" alt="screen shot 2018-11-10 at 17 47 07" src="https://user-images.githubusercontent.com/426437/48378653-35f42900-e686-11e8-87d8-5018cf7b1be5.png">

**Environment**:
- Argo version: v2.2.1

**Comment by David-Development** [comment]
As I'm working on workflows that are quite big and require lots of parallelization, I'm facing a similar problem. Would it be possible to merge all parallel nodes together and display a small "number of tasks" icon over it (like apple mail does it with unread emails in the dock)? 

I think the visualization gets a little more interesting if one of the tasks fails..

I'm using a `dag` instead of tasks. I'm achieving my parallelism by using the `withSequence` keyword. However when using a level of parallelism of 18, the graph is already packed. If I go up to 128 or more the graph is not very helpful anymore (even on 30% zoom level).

I guess for the `withSequence` option the same argument applies as for the tasks and `parallelism` attribute, right? 


The following screenshot demonstrated that it's impossible to identify the relationships between certain tasks as the ordering is messed up as well. And I was only using a parallelism of 4 here. I guess you can imagine what it'll look like when using a parallelism of 128.

![screenshot from 2018-12-10 17-38-49](https://user-images.githubusercontent.com/4489723/49747081-e6177a80-fca2-11e8-90b7-ef00b296fb03.png)

**Comment by g-io** [comment]
I'm dealing with the same issues. [Apache Nifi](https://nifi.apache.org/) is solving this with a number per status on a condensed/folded view item, with the option to expand into sub-items. Obviously this works better conceptually if the parallelized tasks are of the same type.

@David-Development just out of curiosity, do you experience performance issues with the performance in your workflows with large amounts of tasks?
I have run lightweight containers (alpine) with simple bash echo and I'm finding that the time to completion can take multiple seconds or more for each single task.
In time critical workflows this adds up with the depth of the execution tree and the amount of tasks which need to get scheduled subsequently onto resources limited by a parallelism threshold.

I wonder if some config in my setup is wrong, or if argo is not the right tool to schedule 1000s of small, time critical jobs with dependencies.

**Comment by David-Development** [comment]
@g-io Yes, I do notice some slowdown however our steps are long-running (each step/task is usually running about an hour). Therefore the overhead isn't too much of a problem for us. However for time critical applications this can indeed be a problem. I guess this is a general problem of containerized workflow-systems/engines as the task of scheduling the tasks is somewhat depending on how fast kubernetes schedules them (from what I understood so far).

If I got the concept of Nifi right, you can't use Docker Containers as steps, right? I looked into using Digdag and Pachyderm as well. Pachyderms core is open-source however their Web-UI isn't. However the community is great and they have some neat features such as data provenance, incremental training etc. Always depends on your use-case and if you want to move data between tasks as well (files). If you have another external storage mechanism implemented already you might be better off using other workflow-engines (such as digdag) as this introduces some small overhead as well (storing workflows output etc.). However digdag doesn't scale as good as running it in a cluster is not officially documented. I got it working by using docker-swarm but it's not perfect. If you're interested, just let me know. Also, not sure if you've seen this list of a few workflow-systems out there: https://github.com/common-workflow-language/common-workflow-language/wiki/Existing-Workflow-systems. However I didn't find this list very useful as many of those engines are not developed anymore or are poorly documented. Send me an e-mail if you're interested in my current research results (I'm comparing workflow-systems in my thesis).

**Comment by simster7** [comment]
Hopefully fixed by #2319 and #2349
