### ISSUE TITLE
Timeline for Argo 2.2.2?

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#1212]
Is it possible to have regular releases, so it's predictable when fixes are getting released?

**Comment by jessesuen** [comment]
@Ark-kun yes, it's a problem right now since our attention has been split between multiple projects (both internal and external). We're working on fixing that with additional staffing, as well as trying to start to rely more on external contributors.

But to answer your question. We will be releasing v2.3 as soon as possible. Here is what's being targeted: https://github.com/argoproj/argo/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.3

**Comment by xianlubird** [comment]
Is there somewhere or channel for external contributors to join?
I want to contribute some power to argo project.   Thanks.

@jessesuen

**Comment by xianlubird** [comment]
@jessesuen  Can you select a leader and we can work together to release a new version.  

I think many contributors want to help release and fix on argo.

You can organize  a virtual team   and we can work together.

**Comment by SeriousSem** [comment]
@xianlubird that is a great suggestions. As Argo fan/user I'm a little bit concerned about involvement of the owners in this project. A lot of great PRs are open but nothing happens with it for months. I understand that the owners have their own intern work but may be it makes sense then to involve more community members in the project management?

**Comment by xianlubird** [comment]
Wait for your decision...    @jessesuen

**Comment by alexec** [comment]
v2.2.2 has been released.
