### ISSUE TITLE
How to enable Docker image caching when using DIND?

### ISSUE THREAD

**Issue by AndriiNeverov** [argoproj/argo#1446]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Question

**What happened**:

The image is pulled every time which can be quite time consuming

**What you expected to happen**:

In case the image is already in host' Docker cache, it should not be pulled

**How to reproduce it (as minimally and precisely as possible)**:

https://argoproj.github.io/docs/argo/examples/readme.html#docker-in-docker-using-sidecars

**Comment by paveq** [comment]
One partial solution we had before is to mount Docker sidecar's graph storage volume using hostPath, so that caching would happen if docker build happens to be scheduled to exactly same node.

But this had huge drawback of failing builds when multiple builds happen parallel, as graph storage can't really be shared by two concurrent Docker daemons.
