### ISSUE TITLE
Ability to collect step level metrics

### ISSUE THREAD

**Issue by alexmt** [argoproj/argo#1539]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature Request

**What happened**: A workflow user should be able to collect step level metrics. Two groups of metrics had been requested:

* Basic step level metrics like step name, duration, phase.
* Custom metrics. In addition to basic step metrics, the user wants to be able to add custom tags. Following examples were given: 
  * size of file from s3 bucket processed by the step.
  * error code of downsteam service which caused step to fail.

Ideally, the user wants to have a way to declaratively define custom tags for the metric. E.g. specify output parameters which are supposed to be used as tag value.

**Comment by sandeepbhojwani** [comment]
In addition to being able to add custom tags to step level metrics, we may want to consider support for step level containers to emit new custom metrics

**Comment by tekenstam** [comment]
Would this allow a workflow to send metrics to Prometheus through the [pushgateway](https://github.com/prometheus/pushgateway/blob/master/README.md)?

**Comment by sandeepbhojwani** [comment]
I think, in this case, workflow controller will act like a pushgateway

**Comment by simster7** [comment]
@tekenstam @sandeepbhojwani Hey guys (and anybody else interested in this issue)! Could I ask your opinions on the current implementation of this issue here: https://github.com/argoproj/argo/pull/1853#issuecomment-579843428? Curious what you think of the current spec. I would also appreciate it if you could read and pitch in on this discussion from slack: https://argoproj.slack.com/archives/C8J6SGN12/p1580750477250500

**Comment by dseapy** [comment]
I'm curious what everyone thinks about the following changes.  It's a bit more complex, but provide a bit more flexibility.

Each step can emit metrics from a file on a path specified, as is currently done in the PR.  However, instead of this file containing a number, it contains all the prometheus metrics the step wishes to expose (https://github.com/prometheus/node_exporter#textfile-collector).

The workflow-controller can then optionally add any additional labels it desires to each metric, and expose those metrics via http to prometheus.

The workflow-controller would want to ensure it doesn't add high-cardinality labels (https://www.robustperception.io/cardinality-is-key, https://prometheus.io/docs/practices/naming/#labels).

Label values shouldn't identify the workflow uniquely, as that would require high-cardinality label values.  If requiring metrics for a specific workflow/step, one should enable and query the workflow archive (https://github.com/argoproj/argo/issues/2144).  In 2144, argo would convert the metrics into json using prometheus' prom2json (https://github.com/prometheus/prom2json), so that it could be stored and queried in the workflow json (https://github.com/argoproj/argo/issues/2133).

Removing the `name` and `step_name`, would cause duplicate metrics and the workflow controller would only want to expose the latest one for any existing workflow in kubernetes.  Argo users should be made aware that they should not use unbounded sets of label values.

**Comment by alexec** [comment]
Close in favour #2203.
