### ISSUE TITLE
Argo installer work for supporting user provided Kubernetes clusters

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#161]
Users could have their own existing Kubernetes clusters and would want to install the Argo platform on these clusters (see #147). In these cases, the users should be able to provide the kubeconfig of their existing cluster and the installer should simply install Argo on that cluster.

The user will have to at least provide (a) the kubeconfig file for the cluster and (b) 2 buckets, one for metadata and one for data.

**Comment by abhinavdas** [comment]
I prefer the bucket configuration to be something that is done when argo is up and running. Maybe from the UI. While we currently use bucket for storing config, I think we can use a k8s `configmap` to store our ClusterConfig. This can later be backed to an artifact bucket but that is more a backup than a central source of truth.

**Comment by zhan849** [comment]
I would prefer bucket as central source of truth as we need to deal with cluster when master is not running, i.e. a paused cluster, or a cluster is upgrading. Adding another layer of persistence will make it more difficult to keep them synchronized.

**Comment by zhan849** [comment]
also, a run time bucket change will need more complicated coordinations cluster wide, i.e. our WFE, axmon, applet needs to have real time update of buckets, which makes it hard for artifact management. Plus, since changing bucket also involves node level / bucket level IAM policy change, which I don't think would be a common use case. So specifying bucket at install level would be the cleanest solution

**Comment by shrinandj** [comment]
Completed with 3afb691.
