### ISSUE TITLE
Disable user for changing security groups via Argo UI

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#165]
Argo's system settings allow the user to change/edit security groups. This is fine on clusters that Argo provisions itself. But for user provisioned clusters, this should be disabled.

**Comment by abhinavdas** [comment]
I think in general, this should be moved out of ARGO UI. Managed ELB allows users to change security groups directly. I don't see a good reason for leaving this as an option for cluster provisioned by argo tools either.

**Comment by zhan849** [comment]
Since we are still using Kubernetes provisioned ELB for axops, for user provisioned cluster, we should only change that of axops service object (type LoadBalancer).

Also, if we are going the way of running argo on `any` Kubernetes cluster, I doubt if idea of "Managed ELB" can still be applied or not, as Kubernetes is already handling resource provisioning, and it gives us good APIs about what to provision. (Or we need to handle AWS/GCP/Azure as well)

**Comment by shrinandj** [comment]
There are no managed ELBs on user-provided K8S clusters on AWs.
