### ISSUE TITLE
Dind containers should use emptyDir on user provisioned clusters

### ISSUE THREAD

**Issue by shrinandj** [argoproj/argo#167]
On Kubernetes clusters created by Argo, DinD containers are configured to use the flexVolume plugin. However, if the user provisioned the Kubernetes cluster himself and simply installed Argo on it, the flexVolume plugin won't be present on the host. In such cases, the DinD container should revert to using `emptyDir`.

**Comment by abhinavdas** [comment]
We might want to add more options to dind support so that users have the flexibility of defining which storage provider to use for dind graph storage. We should support a subset of kubernetes volume options. This will allow the user to use your flex volume plugin or persistent volumes as long as they define how they want to use these volumes. Supporting this would be in the worst case as bad as emptyDir (no-caching) as long as we do not allow volumes that can be shared concurrently.
