### ISSUE TITLE
Discrepancy in examples for steps syntax 

### ISSUE THREAD

**Issue by DanGolding** [argoproj/argo#1837]
**Is this a BUG REPORT or FEATURE REQUEST?**: Possible error in the documentation

**What happened**: In many of the examples, the steps are written both with two hyphens as in `- - name` ([example](https://github.com/argoproj/argo/blob/master/examples/retry-with-steps.yaml#L11)) and in the same list, with one hyphen as in `  - name` ([example](https://github.com/argoproj/argo/blob/master/examples/retry-with-steps.yaml#L15)). The same pattern can be seen in the [readme](https://github.com/argoproj/argo/blob/master/examples/README.md#steps). I assume the two hyphens are typos 🤔 ?

**What you expected to happen**: The docs to be consistent and follow yaml best practice

**Comment by simster7** [comment]
This is actually intended. The `steps` spec is a list of lists, all of the steps in each element of the parent list will be run in parallel and once they are all done, the next set of elements in the parent list will be run.

In the example you cite:
https://github.com/argoproj/argo/blob/b3d458504b319b3b02b82a872a5e13c59cb3128f/examples/retry-with-steps.yaml#L11-L16

`hello1` will be run first (since it is a part of the first element of the parent list). After it's done, `hello2a` and `hello2b` will be run _in parallel_ (since they are both part of the second element of the parent list).

**Comment by DanGolding** [comment]
Ah, thanks!
