### ISSUE TITLE
Empty array as args in yaml file is not handled correctly

### ISSUE THREAD

**Issue by sytianhe** [argoproj/argo#209]
In yaml,
`- BUILD:
    image: applatix/claudia-builder:latest
    command: [/src/build.py]
    args: []`

After axops processing it, it shows up as there is no args.
![screen shot 2017-09-12 at 4 15 51 pm](https://user-images.githubusercontent.com/605748/30352616-c0dfccf0-97d5-11e7-8aa4-72f0b35bc7f0.png)

**Comment by jessesuen** [comment]
This turns out to be golang's json `omitempty` behavior, which we use for args, command, and other string arrays:

```
type ContainerTemplate struct {
...
	Command         []string            `json:"command,omitempty"`
	Args            []string            `json:"args,omitempty"`
...
}
```

The documentation states:

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

I verified, that during unmarshaling, the empty array is preserved in the datastructure form. However when marshalling back to json, the args is omitted if the array is empty. Golang json package has no way to be more specific about nulls vs. empty arrays.

In order to fix this, we will probably need to alias `[]string` with our own definition with a custom MarshalJSON() method.

**Comment by jessesuen** [comment]
I should also add, simply removing the `omitempty` from the json annotation is not desirable since we truly want to omit the value if the user did not supply it.

**Comment by jessesuen** [comment]
> In order to fix this, we will probably need to alias []string with our own definition with a custom MarshalJSON() method.

Actually, we would need to implement MarshalJSON() on the surrounding type (i.e. ContainerTemplate) for it to intelligently omit args depending on if it's an empty array or nil. There is a [proposal](https://github.com/golang/go/issues/11939) for being able to control this in the encoding/json package, but it is not implemented.

We could solve this by making `[]string` become `*[]string`, but I'd rather not do that since the use case for having an empty args array is quite limited, and I believe that this can be worked around.

Closing this wontfix
