### ISSUE TITLE
Argo workflow not running

### ISSUE THREAD

**Issue by kabilan6** [argoproj/argo#2126]
# Summary

Argo workflow in pending status. Installed Argo 2.4.3 on cluster. Verified workflow controller in running status and created rolebinding with clusterrole =admin  but the sample workflows in pending status.

when i created new clusterrolebinding with clusterole=admin , the workflow ran and Succeeded . Does Argo need clusterrolebinding privileges to run the workflow.?

**Comment by alexec** [comment]
It needs some role binding to run. If you're running in cluster-scoped mode (i.e. `install.yaml`) rather than namespace-scope moder (`namespace-install.yaml`) then you will need a cluster role binding, otherwise a role binding.

Read more https://github.com/argoproj/argo/blob/master/docs/workflow-rbac.md

**Comment by alexec** [comment]
Please re-open if still an issue.
