### ISSUE TITLE
cluster state on S3 is corrupt (Running when it is not)

### ISSUE THREAD

**Issue by abhinavdas** [argoproj/argo#226]
On cluster dast1, the cluster state shows up as `running`
`aws s3 cp --profile dev s3://applatix-cluster-8aac53a5-b947-5848-b221-07255411e359-0/dast1/1af73b3a-9757-11e7-9fc9-025000000001/current_state -` when the cluster is actually not running. 

```
$> an
------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                     DescribeInstances                                                                    |
+----------------------------------------------------+----------------------+----------+--------------+--------------------------------------------+-------+
|  dast1-1af73b3a-9757-11e7-9fc9-025000000001-master |  i-0b49020ef3314ef01 |  stopped |  52.38.97.60 |  ip-172-20-0-9.us-west-2.compute.internal  |  None |
+----------------------------------------------------+----------------------+----------+--------------+--------------------------------------------+-------+
```

I suppose this can happen when cluster is stopped but state file is not updated. Looks like the order of operations is a problem here...

This is code from common/python/ax/cluster_management/app/cluster_pauser.py
``` 
 68     def pre_run(self):
 69         if self._csm.is_paused():
 70             logger.info("Cluster is already paused.")
 71             sys.exit(0)
 72
 73         # This is for backward compatibility
 74         if not check_cluster_staging(cluster_info_obj=self._cluster_info, stage="stage2"):
 75             raise RuntimeError("Cluster is not successfully installed: Stage2 information missing! Operation aborted.")
 76         self._csm.do_pause()
 77         self._persist_cluster_state_if_needed()
```
If do_pause finishes but somehow the persist_cluster_state_if_needed fails (could be due to OOM, or lost internet connectivity) then we can run into this state. The solution I think is to persist a cluster state of `pausing` before doing pause and then convert it to `paused` when it all succeeds.

**Comment by zhan849** [comment]
The example you provided does not exist, as if do_pause() finished and we failed to persist, cluster state is still Running. If we re-execute the command, it will try to do Running -> Pausing transition, and then persist again.


The problem you saw was because you created cluster with a v1.1 cluster manager, but someone tried to pause it using v1.0 cluster manager.Since v1.0 cluster manager does not have concept of cluster state, it will pause the cluster without modifying state. When you try to resume the cluster with a v1.1+ cluster manager, it will see that the cluster is still in Running state and terminate, so your cluster will not be actually resumed.

As discussed offline, a working proposal is to abort operation if the cluster's version is newer than the cluster manager container version. I will work it out but we should still manually prevent 1.0 rabbit hole

**Comment by abhinavdas** [comment]
As pointed to by @zhan849 it is not a bug.
