### ISSUE TITLE
How to setup argo cli on windows

### ISSUE THREAD

**Issue by lueenavarro** [argoproj/argo#2683]
I see that there is a file ( argo-windows-amd64 ) for the windows cli here https://github.com/argoproj/argo/release but I cannot find any instruction on how to set it up on windows.

**Comment by lueenavarro** [comment]
Hi for those wondering, here is how to do it:
1. Rename the argo-windows-amd64 to argo.exe
2. Place it in a folder (eg. C:\argo-cli)
3. Open the environment variables setting and add the folder under System Variables > PATH
4. To test, open cmd and type `argo version`

**Comment by alexec** [comment]
The core team does not use Windows, so it'd be great if you could share what works for you.

**Comment by medianick** [comment]
For what it's worth, I placed the downloaded, renamed `argo.exe` into my `C:\ProgramData\chocolatey\bin` folder -- since it was already in the PATH, and in an ideal world I'd have it installed through Chocolatey ([which has only an old version](https://chocolatey.org/packages/argocd)) -- and that let me avoid another folder and addition to the PATH. Works beautifully, thanks to @lueenavarro's tip.

**Comment by jstarman** [comment]
Update: the [windows .exe](https://github.com/argoproj/argo-workflows/releases/latest) is now packaged in a .gz and will need to be extracted via [7-zip](https://www.7-zip.org/) or similar. Then follow above.
