### ISSUE TITLE
Package v2.5.2+incompatible and Kubernetes 1.18

### ISSUE THREAD

**Issue by jsenon** [argoproj/argo#2962]
# Summary

Compatibility with Kubernetes 1.18

# Motivation

It seems that the package v2.5.2+incompatible is not compatible with new version of Kubernetes 1.18 and the new `context.Context`. Do you have plan to update your package for Kubernetes 1.18 ?

For example in this package: https://pkg.go.dev/github.com/argoproj/argo@v2.5.2+incompatible/pkg/apis/workflow/v1alpha1?tab=doc

**Comment by alexec** [comment]
We do not support v2.5 anymore. Please try with the stable version - v2.7.

**Comment by jsenon** [comment]
Are you talking about golang package? Seems that version 2.7 is not published, the latest version on godoc is 2.5.2

**Comment by jsenon** [comment]
If we force module with:

`go get github.com/argoproj/argo@master  `

I've still have issue with kubernetes client 1.18 and the context

**Comment by yoichiwo7** [comment]
This is because argo-workflow after `v2.5.2` moved to go module.
Go module with major version 2 or higher needs version suffix like `/v2` in go.mod:

```go
module github.com/argoproj/argo/v2
```

Following StackOverflow answer summarizes this topic well.
https://stackoverflow.com/a/57372286

Until argo-workflow supports this module version scheme, you can use matching commit hash in `go get` command. For example if you want to use argo-workflow v2.8.0 module, you can do it by following command. You can check matching commit hash in [releases/tags page](https://github.com/argoproj/argo/releases).

```
go get github.com/argoproj/argo@8f696174746ed01b9bf1941ad03da62d312df641
```

**Comment by jsenon** [comment]
Thanks @yoichiwo7 but I don't know if argo has been updated in order to be compatible with Kubernetes 1.18 and the context. 
And also to understand why the go doc is not updated as well.

**Comment by yoichiwo7** [comment]
I think the answer is no.
argo-workflow v2.8.0 uses  `cleint-go: release-12.0` module which is based on Kubernetes v1.15. And it still uses `golang.org/x/net/context`.
By the way, I'm curious what kind of problem you are facing. I think putting use-cases and errors might be helpful to solve the issue.

As for go doc, it's not updated because the current argo-workflow doesn't follow valid go module version scheme; which I mentioned above. If argo-workflow fixes this, the go doc will also be updated again.

**Comment by alexec** [comment]
See #2611 

We could do with some help on fixing this - @jsenon or @yoichiwo7 would you like to help with fixing the `go.mod` problem?

**Comment by yoichiwo7** [comment]
@alexec 
Yes, I would like to help with it.

**Comment by iven** [comment]
I've also meet an error with kubernetes client 1.18 and the context:

```
../go/pkg/mod/github.com/argoproj/argo@v0.0.0-20201015222631-076bf89c4658/pkg/client/clientset/versioned/typed/workflow/v1alpha1/cronworkflow.go:74:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("cronworkflows"
).VersionedParams(&opts, scheme.ParameterCodec).Timeout(timeout).Do
        have ()
        want (context.Context)
```

It seems argo depends on controller-tools v0.3.0, which depends client-go v0.18.2, which is conflicted with argo's dependency client-go v0.17.8.

The workaround I found is(put this in your `go.mod`):
```
replace sigs.k8s.io/controller-tools => sigs.k8s.io/controller-tools v0.2.9
```

Hope it helps.

**Comment by shahadarsh** [comment]
Hey folks, I'm getting the same error. 

@iven I tried your workaround but it didn't work. I also tried the following without any luck. Any help would be appreciated. 

`go get github.com/argoproj/argo@8f696174746ed01b9bf1941ad03da62d312df641`
