### ISSUE TITLE
retryStrategy on GKE preemptive node does't work

### ISSUE THREAD

**Issue by fabio-rigato** [argoproj/argo#3211]
Hi guys,

this issue is still active.

argo version: 2.8.1 on GKE

In particular, if a pod failed is marked with a red /!\ (pod deleted) and the workflow is running forever.

this is my retry strategy:

**retryStrategy:
      limit: 4
      retryPolicy: "Always"
      backoff:
        duration: "12s"
        factor: 5
        maxDuration: "200m"**

**Comment by simster7** [comment]
Hi @fabio-rigato, it seems that we accidentally didn't include the fix for this (https://github.com/argoproj/argo/pull/2976) in `v2.8.1`.

The fix is present on `v2.9.0-rc1`, but that is a pre-release and is not recommended for production systems yet. I will look into releasing a `v2.8.2` with the fix soon.

**Comment by fabio-rigato** [comment]
Hi @simster7 thanks a lot for your fast reply.
Happy to hear that mate!
I hope you a great day!
All the best
Fabio

**Comment by fabio-rigato** [comment]
Hey @simster7 do you have any ETA for v2.8.2 release? because this issue is affecting us in production and we need to upgrade asap.
Thanks for your effort.
Cheers.
Fabio

**Comment by simster7** [comment]
I’ll try to get a release out this week

**Comment by fabio-rigato** [comment]
thanks for that @simster7

**Comment by alexec** [comment]
#3214

**Comment by simster7** [comment]
Fixed in #2976
