### ISSUE TITLE
argo cluster install failed to create S3 bucket

### ISSUE THREAD

**Issue by edlee2121** [argoproj/argo#358]
Argo cluster install in us-west-2 failed to create the S3 bucket. We created the bucket by hand to complete the install. This seems odd since we install clusters in us-west-2 all the time.

One interesting note, our user may have first tried to install in us-east-1 before completing the install in us-west-2. It may be possible that something didn't get cleaned up properly and confused the second install.

Note that when creating buckets in regions outside us-east-1, one must specify a location constraint.
https://stackoverflow.com/questions/42936553/cannot-create-amazon-s3-bucket-in-specified-region

**Comment by shrinandj** [comment]
If an installation was attempted in one region, the installer creates a bucket in that region. To re-install in a different region, the user needs to first uninstall the cluster (which will delete the bucket). Then the installation should work in the alternate region.

Since, bucket names are global in AWS, some time needs to pass before AWS can create the bucket with the same name in a different region. Most likely, this is what happened here.

We should document that if the installation failed in one-region, the user should uninstall first and re-attempt installation in a different region after a few minutes.

**Comment by alexmt** [comment]
Looks like https://github.com/argoproj/argo/issues/428 is caused by the same issue. @edlee2121 can you please confirm ?

**Comment by edlee2121** [comment]
@alexmt Yes, it could be the same issue.

**Comment by edlee2121** [comment]
Currently, you can only instal Argo V 1.x in one region at a time.
