### ISSUE TITLE
Pagesize = all not woking on Archived Workflow View

### ISSUE THREAD

**Issue by xinbinhuang** [argoproj/argo#3775]
## Summary 

What happened/what you expected to happen?

In the Archived Workflow View, the default page size is `10` and it cannot be changed to `all`. I think it will be better to be consistent with the Timeline view: default `all`

Also, I feel like the `Archived Workflow` is somehow redundant to the `Timeline View`. I wonder what's the actual use case for it?

## Diagnostics

What version of Argo Workflows are you running?

2.9.3

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by alexec** [comment]
A default of `all` would crash the browser of users with many archived workflows. However, it should be possible to change to `all`. Can you confirm if you have had a problem with this?

**Comment by xinbinhuang** [comment]
> A default of `all` would crash the browser of users with many archived workflows. However, it should be possible to change to `all`. Can you confirm if you have had a problem with this?

I can change to `500` but not `all`..

**Comment by alexec** [comment]
> I can change to `500` but not `all`..

Screenshot? Diagnostics?

**Comment by xinbinhuang** [comment]
Here is the error
![image](https://user-images.githubusercontent.com/27927454/90284366-c0068e00-de26-11ea-88ca-360c0661d193.png)

**Comment by alexec** [comment]
Available for testing in [v2.10.0-rc1](https://github.com/argoproj/argo/releases/tag/v2.11.0-rc1).

**Comment by claas-fridtjof-lisowski** [comment]
I'm still seeing this error in v2.11.1 when I choose to show "all" results

```
react-dom.production.min.js:198 TypeError: Cannot read property 'toString' of null
    at t.get (archived-workflow-list.tsx:126)
    at t.saveHistory (archived-workflow-list.tsx:132)
    at oa (react-dom.production.min.js:193)
    at ra (react-dom.production.min.js:193)
    at Ha (react-dom.production.min.js:216)
    at Va (react-dom.production.min.js:220)
    at react-dom.production.min.js:250
    at Object.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Ts (react-dom.production.min.js:250)
    at Es (react-dom.production.min.js:249)
```

**Comment by dcherman** [comment]
@alexec Can we reopen this one?  I'm running into this as well (essentially the same stacktrace).

The problem is here:

https://github.com/argoproj/argo/blob/a441a97bd53a92b8cc5fb918edd1f66701d1cf5c/ui/src/app/shared/components/pagination-panel.tsx#L38-L39

The value of `all` is piped through `parseLimit`, however `parseLimit` returns `null` for values that it's unable to parse.

That causes this line to throw:

https://github.com/argoproj/argo/blob/1cc68d8939a7e144a798687f6d8b8ecc8c0f4195/ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx#L126

I can fix this later today, just need to figure out what value the backend expects when the value should be `all`.  If you happen to know that off the top of your head, that'd be very helpful

**Comment by alexec** [comment]
I think `all` should mean we pass `null` to the backend.
