### ISSUE TITLE
Help pods understand that they're being terminated

### ISSUE THREAD

**Issue by Ark-kun** [argoproj/argo#3896]
There are two main reasons why pod is being terminated: Either the user has requested this or not.
FOr some scenarios it's important to distinguish between those two. For example, if the pod has started some long-running cloud job outside the cluster, the user probably wants that job terminated when they terminate Argo Workflow.

Kubernetes supports graceful termination by sending the signal to the containerized program.

However it's not easy for the program to understand the reason for the signal. Is node being pre-empted? Did user click "Terminate"?

It would be useful if Argo communicated the user-initiated termination to the containers.

It should be trivial to at least **add label to the pod when it's being intentionally terminated**. That information can be made available to the containerized program using Kubernetes' Downward API.

I wonder whether Argo can send signals to the containers as well.

**Comment by simster7** [comment]
If Argo terminates a Pod due to a user-defined action, such as using "Stop" or "Terminate", or setting a `workflowDeadline`, then Argo will do the following:

1. Argo will add an annotation to the affected Pod which value is of type `ExecutionControl`:

    https://github.com/argoproj/argo/blob/6e82bf382a0b41df46db2cc3a1a3925d009f42e1/workflow/common/common.go#L162-L170

    The annotation gets added here:

    https://github.com/argoproj/argo/blob/6e82bf382a0b41df46db2cc3a1a3925d009f42e1/workflow/controller/exec_control.go#L134-L140

2. Argo will send a `SIGURS2` signal to either the Main or Wait containers of the Pod telling the Pod to listen to fetch its execution control annotation as it was just updated.

3. The Wait container will monitor the execution control annotation, and if necessary it will kill the main container by issuing a `SIGTERM` signal to the main container, waiting 30 seconds, then sending a `SIGKILL` signal to the main container. The signals or the timing between them is currently not customizable.

> It should be trivial to at least add label to the pod when it's being intentionally terminated. That information can be made available to the containerized program using Kubernetes' Downward API.

We know this is not the exact ask, but as a current workaround, the container within a Pod can check for the existence of the Execution Control annotation to determine if it has been shut down by user-defined actions in Argo vs. an external request.

Does this help?

**Comment by simster7** [comment]
Will be closing this, but feel free to reopen if your question wasn't answered.
