### ISSUE TITLE
Negative Prometheus metrics

### ISSUE THREAD

**Issue by alexec** [argoproj/argo#3902]
## Summary 

Negative values for metrics which should only every be positive.

![prom-bug](https://user-images.githubusercontent.com/1142830/91666652-5b4c6400-eab3-11ea-814c-472a6cd13d9d.png)

## Diagnostics

`inf-wb`

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
This should have been fixed some versions ago. Do you have any steps to reproduce?

**Comment by alexec** [comment]
I'm not 100% sure this is a `master` issue, I'm doing some stress testing or my `inf-wb` branch and update.

**Comment by alexec** [comment]
I'm wondering if this is an informer issue. It's a become a bit clearer we can get duplicate events from the informer.

@simster7 do you want to take ownership? Or I'll look into this.

**Comment by simster7** [comment]
Hi @pacospace, I just confirmed that the fix for this issue (https://github.com/argoproj/argo/pull/3350) was introduced in `v2.10.0`. Please upgrade for the fix.

@alexec Our current approach is resistant to multiple events from the informer. Until we can confirm that this issue persists on builds with #3350 present, then I think this is largely a non-issue. I'd be happy to take ownership of this though.

**Comment by pacospace** [comment]
> Hi @pacospace, I just confirmed that the fix for this issue (#3350) was introduced in `v2.10.0`. Please upgrade for the fix.
> 

Thank you very much @simster7!!

**Comment by simster7** [comment]
I suggest we close this unless it comes up again

**Comment by terrytangyuan** [comment]
We are still seeing this in one of our clusters for v2.12 argo-workflows controller.
