### ISSUE TITLE
can argo event be substituted by normal rest api?

### ISSUE THREAD

**Issue by gtarcoder** [argoproj/argo#3968]
# Summary

Here is the description of argo event, https://argoproj.github.io/argo/events/. I find it can only do these two things, "These events can submit workflow templates or cluster workflow templates."

I am wondering if event is redundant since we can submit workflow using argo rest api?

**Comment by alexec** [comment]
Short answer - no. The fit different use cases. You can submit a workflow template from another system using the REST API in v2.10, but only if you have control of that system. I.e. you can change it so that it send the specific HTTP request needed. If you do not control that system (e.g. Github, Gitlab, etc etc) but you can configure it to send post to webhooks, then you may use this system.
