### ISSUE TITLE
"RETRY" button is disabled when continueOn: {failed:true}  on a DAGTask or onExit

### ISSUE THREAD

**Issue by nojvek** [argoproj/argo#4513]
# Summary

What change needs making?

Without continue on, retry is enabled for a DAG, but adding continueOn disables RETRY. Not sure why. I would expect that RETRY finds the first failing node, and then retries the failing node + all nodes connected to it.

# Use Cases

When would you use this?

We have tasks that are like soft fails e.g check tests. Even if tests fail we want to proceed to next node. However we want to offer user the option to re-run the failed node.

![image](https://user-images.githubusercontent.com/1018196/98783673-d0d78900-23ae-11eb-85d8-3fd837dd0c0b.png)

Even though "check-ci" is a failed step, there is no RETRY button

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

**Comment by simster7** [comment]
`Retry` is only enabled if the workflow as a whole fails (i.e. the top source node is failed). Since you had `continueOn` enabled, then the workflow as a whole did not fail, leaving the `Retry` disabled. We might explore enabling retry when this is the case as well.

However, if you want to ensure that a said step is successful, then it seems like you shouldn't be using `continueOn`. Can you elaborate more on your use case?
