### ISSUE TITLE
Error when attempting to install argo v2 on kubernetes v1.7 and below

### ISSUE THREAD

**Issue by francis-ax** [argoproj/argo#473]
argo v2 failed to install on kubernetes v1.7.x, tried both minikube and gke.

```
Francis-Macbook-Pro:gke francis$ kubectl get nodes
NAME                                          STATUS    AGE       VERSION
gke-fh-gke178-01-default-pool-4baedd7c-nc5v   Ready     39s       v1.7.8-gke.0
gke-fh-gke178-01-default-pool-4baedd7c-pf53   Ready     39s       v1.7.8-gke.0
Francis-Macbook-Pro:gke francis$ ~/bin/argo2 install
Installing into namespace 'kube-system'
ConfigMap 'workflow-controller-configmap' created
FATA[0000] the server could not find the requested resource 
```

**Comment by jessesuen** [comment]
This is known limitation. We currently intentionally do not support v1.7 because CRDs in 1.7 does not support proper cascading deletion of CRDs and their child resources. With 1.8, when you delete a workflow, it will subsequently delete all children because 1.8 obeys the ownership references that we set up when creating the pods. I think the best we should do is improve the installer to indicate that 1.8 is a requirement.

**Comment by pratulw** [comment]
We will document the support is 1.8 and above.

**Comment by jessesuen** [comment]
@shrinandj can you take this as part of upcoming installer fixes
