### ISSUE TITLE
Set service account for workflow steps?

### ISSUE THREAD

**Issue by jlewi** [argoproj/argo#634]
Is it possible to set the service account used by workflow steps?

**Comment by jessesuen** [comment]
For container templates, it is not currently possible -- we would need to introduce a field to carry forward into the pod spec.
For resource templates, the manifest can be freeform, so it should work by virtue of adding the `serviceAccountName: myserviceaccount` to the spec.

Is there a use case for having different steps using different service accounts?

**Comment by jlewi** [comment]
I want to use the same service account for all steps. Right now its using the default account and I didn't see a way to set this either at the step or workflow level. I think it would be useful to set it at the workflow level since different workflows might need different permissions.

**Comment by jessesuen** [comment]
I agree -- this is definitely needed at very least in the workflow level. This should be simple to add `spec.serviceAccountName` which gets carried forward to the pod spec.

**Comment by DenysSkrytskyi** [comment]
And was there any change in Argo Workflow v3.5.4 (compared to v3.4.4) that in the nested Workflow Template: the Service Account specified in outer Workflow is not transferred to use in inner Workflow? 
as I specified the service account in outer template and while running I get error that inner template uses <default> service account


Example : 

`
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: nested-example-workflow
spec:
  serviceAccountName: workflow-sa
  imagePullSecrets:
    - name: test-secret
  entrypoint: outer-template
  templates:
    - name: outer-template
      steps:
        - - name: step1
            template: inner-template
        - - name: step2
            template: inner-template
    - name: inner-template
      resource:
        action: create
        manifest: |
          apiVersion: argoproj.io/v1alpha1
          kind: Workflow
          metadata:
            generateName: workflow-of-workflows-1-
          spec:
            entrypoint: whalesay-template
            imagePullSecrets:
              - name: test-secret
            templates:
              - name: whalesay-template
                container:
                  image: docker/whalesay
                  command: [cowsay]
                  args: ["hello-world"]
        successCondition: status.phase == Succeeded
        failureCondition: status.phase in (Failed, Error)
`

**Comment by agilgur5** [comment]
> And was there any change in Argo Workflow v3.5.4 (compared to v3.4.4)

This is an issue from several years ago that far predates both of these versions, so I'm not sure why you left a comment here specifically.

Also, even between those two versions, there's quite a lot of things different. When debugging something, it's useful to have the most minimal diff possible, for instance, "3.4.4 vs 3.4.5".

> specified in outer Workflow is not transferred to use in inner Workflow?

It should never be transferred. A resource template just has an arbitrary manifest, which can contain any resource, and has no specific handling for Workflows of Workflows. Arbitrary resources do not even necessarily have SAs. It is up to the user to specify everything they need in a resource template, including their SA, which was also mentioned 7 years ago [above](https://github.com/argoproj/argo-workflows/issues/634#issuecomment-354419234).

This issue was also not about resource templates specifically, it was about steps in a Workflow. The resolving commit allowed an SA to be specified at the top-level of a Workflow for all steps to use.
