### ISSUE TITLE
Resubmitting a suspended workflow does not run past the suspended step

### ISSUE THREAD

**Issue by dvavili** [argoproj/argo#759]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: Resubmitted workflow stays in suspended state as well when it starts off and only proceeds after `maglev workflows resume` is issued.

**What you expected to happen**: Resubmitted workflow should not be suspended

**How to reproduce it (as minimally and precisely as possible)**: Run a workflow. Suspend the workflow and resubmit it.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.0+cc8f35b
  BuildDate: 2018-02-21T19:13:12Z
  GitCommit: cc8f35b636558f98cd2bd885142aa1f8fd94cb75
  GitTreeState: clean
  GoVersion: go1.9.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-02-09T21:51:06Z
  compiler: gc
  gitCommit: d2835416544f298c919e2ead3be3d0864b52323b
  gitTreeState: clean
  gitVersion: v1.9.3
  goVersion: go1.9.4
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-18T09:42:01Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
@dvavili can you clarify the sequence of events that happened? Was this resubmitted in memoized or non-memoized mode?  I actually did not think argo cli supported the resubmission of suspended workflows which are not yet considered completed.

**Comment by dvavili** [comment]
Saw this issue with non-memoized mode.

This is the sequence of steps:
1. Submit a workflow
2. Suspend the workflow
3. Resubmit the workflow (The submitted workflow stays in Running (Suspended) state)

**Comment by jessesuen** [comment]
When you suspended the workflow, is it pre-determined via a suspend template step? or is done manually via argo cli?

**Comment by jessesuen** [comment]
When we resubmit something. We preserve the `workflow.spec` entirely. A manually suspended workflow will have `workflow.spec.suspend: true`, which gets carried over to the new workflow. So the workflow starts off in a suspended state. All that is needed, is to run `argo resume workflow` and the resubmitted workflow will begin execution. I feel that resubmitting something in a suspended state is acceptable behavior, since the CLI clearly indicates the status:

```
$ argo get fun-with-gifs-bht6k
Name:             fun-with-gifs-bht6k
Namespace:        default
ServiceAccount:   default
Status:           Running (Suspended)
Created:          Wed Feb 21 15:17:43 -0800 (10 seconds ago)
Started:          Wed Feb 21 15:17:43 -0800 (10 seconds ago)
Duration:         10 seconds
```

I rather leave the behavior as is, instead of special casing the workflow.spec.suspend in a resubmit. Thoughts?

**Comment by dvavili** [comment]
It makes sense for `argo resubmit <>` to carry over the workflow spec, but not the workflow status. It might be ok for a resubmit with `--memoized` option to carry over the status as well, but it feels like a whole new resubmit should start with a whole new status.

**Comment by jessesuen** [comment]
What you described is the current behavior. `workflow.spec` is always preserved "as-is" in both memoized and non-memoized mode. Status is partially carried over in `--memoized` mode, but only the successful steps. The suspend flag is a spec level field, not a status, because it is under user control. This is why it gets carried over. 

Is there a reason why this wouldn't work for you?
`argo resume $(argo resubmit WORKFLOW -o name)`

I think support for the `-o name` would need to be added, but you get my point.

**Comment by dvavili** [comment]
Didn't realize that suspend was in the spec. That should work and that's how I'm working with it (by filtering out the name). I'll close this issue as there is a workaround and keeps the implementation clean without special filtering.
