### ISSUE TITLE
Resubmit/Retry should update "Started" time

### ISSUE THREAD

**Issue by dvavili** [argoproj/argo#783]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**What happened**: Resubmitting/Retrying a workflow doesn't update start time and the duration is not helpful in that case

**What you expected to happen**: Update start time when resubmitting/retrying a workflow

**How to reproduce it (as minimally and precisely as possible)**: Resubmit/Retry a failed workflow

**Environment**:
- Argo version:
```
$ argo version
argo: v2.1.0+a45bf1b
  BuildDate: 2018-03-07T10:26:25Z
  GitCommit: a45bf1b7558b3eb60ec65d02c166c306e7797a79
  GitTreeState: clean
  GoVersion: go1.9.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-02-07T12:22:21Z
  compiler: gc
  gitCommit: d2835416544f298c919e2ead3be3d0864b52323b
  gitTreeState: clean
  gitVersion: v1.9.3
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-01-18T09:42:01Z
  compiler: gc
  gitCommit: 5fa2db2bd46ac79e5e00a4e6ed24191080aa463b
  gitTreeState: clean
  gitVersion: v1.9.2
  goVersion: go1.9.2
  major: "1"
  minor: "9"
  platform: linux/amd64
```

**Comment by jessesuen** [comment]
For resubmit, startedAt should already be reset, since resubmit always creates a new workflow and I don't believe those fields are carried over. If it doesn't reset it it is a bug. 

For retry, I actually believe it should not carry over the startedAt timestamp because there will exist nodes that occur before the workflow start time (if we reset it). This will in turn mess with the UI timeline view, which may rely on workflow.status.startedAt and node.startedAt for the correct rendering of the timeline.

**Comment by jessesuen** [comment]
Closing since current behavior is desired.
