### ISSUE TITLE
[Feature] Load parameters from a file

### ISSUE THREAD

**Issue by ruiztulio** [argoproj/argo#796]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Feature request

It would be nice to be able to use a file for the parameters and "render" the kubernetes files as part of the workflow. This is useful in cases where you need to deploy the same application but with different images, namespaces, deployments names and so.

My particular use case: We deploy the same application for different customers, bur they have some particular modifications and different docker images as well, also it is useful to use one WF to initialize the tests and demo instances, just get the parameters file and execute  with it. 

I guess that there are other uses for this.

Regards

**Comment by dsmithbauer** [comment]
I would also find this feature useful.  We use a common list of parameters that include Git repos and variables used in the Terraform and Ansible steps of our automation pipeline.  We have a few different workflows and it would be great if we could have a single place to access the parameter list instead of having to maintain it in each workflow.

**Comment by vosmith** [comment]
Hello I was wondering if anyone has picked this issue up.  I'm thinking the only major changes to this would be to the argo-cli right?  And I don't see why it wouldn't be backwards compatible.  Is there any progress here? If not I would be interested in giving it a shot.

**Comment by jessesuen** [comment]
Implemented in 67792eb89e5aa678ffc52540dbc232d8598ce43f
