### ISSUE TITLE
Non-privileged docker builds feature request

### ISSUE THREAD

**Issue by andreimc** [argoproj/argo#827]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

**What happened**:

I am planing to have a lot of argo deployments in the same cluster being separated by namespace and service accounts.

**What you expected to happen**:

Able to run docker in docker without privileged access and have custom secrets.

**Anything else we need to know?**:

https://github.com/GoogleCloudPlatform/kaniko a possible solution for this

**Comment by jessesuen** [comment]
@andreimc our dind example is just a pattern, and is by no means the only solution to doing docker builds. For example, an alternative way of doing this is to have run docker as a daemonset and simply pointed DOCKER_HOST to the node IP. The dind container used in the example (maintained by docker) mandates the use of privileged access for it to function. 

Also, argo workflows are namespaced resources and the workflows are unable to access secrets outside fo their namespace, so the isolation guarantees are the same as what kubernetes provides.

I don't believe there's any feature work needed by argo workflow engine to use something like kaniko. I think it's just another pattern/example. Let us know if you think otherwise.
