### ISSUE TITLE
Workflow steps with non-existant output artifact path will succeed

### ISSUE THREAD

**Issue by jessesuen** [argoproj/argo#897]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG

**What happened**:

It seems Argo will continue down a workflow, even if you specify an output artifact path that doesn't exist. The step which references the non-existant path, will produce a tar.gz file with a zero-byte file.

**What you expected to happen**:

If you specify an output artifact path, and nothing exists at that location, the step should fail.

**Environment**:
- Argo version: v2.1.1

**Comment by jessesuen** [comment]
This is a problem for parameters as well.

**Comment by vicaire** [comment]
For artifacts, could there be an option so that if the file does not exist in the container, it does not fail?

**Comment by jessesuen** [comment]
@vicaire I think that is reasonable. What if we had:
```
outputs:
  artifacts:
  - name: hello
    path: /hello.json
    optional: true
```

**Comment by vicaire** [comment]
That looks great. Thank you!

**Comment by gaoning777** [comment]
Is the "optional" flag currently supported? If so, which version? Thanks

**Comment by Ark-kun** [comment]
I have experience with system that has implemented optional inputs twice, but both times the design was bad.

There needs to be a way to distinguish between two different causes of the lack of argument for an optional input:
* The input is not connected to any upstream (at any point of the upstream hierarchy).
* The input is connected, but some task in the upstream chain has failed. I expect that in this case the downstream tasks are not executed even when the input is optional.

Typical scenario where some bad designs fail:
There is a template with 5 optional input so that the consumer can connect 1 to 5 upstreams without changing the template.
Let's say that 4 inputs have upstream connections.
One of the 4 inputs have upstream failure, so the data is missing.
I expect that the template does not start (not all 4 connected inputs have argument values; even though the inputs are optional, they're connected and become required).
With some problematic designs, the template starts with only 3 out of 4 arguments.

**Comment by jessesuen** [comment]
@Ark-kun yes what you are describing is a best-effort approach to artifacts. This is not that. What was implemented was if a location was specified (e.g. git URL, s3 bucket/key), then the artifact must be downloaded or uploaded successfully for the workflow to succeed. If an artifact location was unspecified/empty, then the artifact must be marked optional, otherwise the workflow will fail.

**Comment by Ark-kun** [comment]
@jessesuen Thanks for the explanation. I now see that this change is about optional outputs while my concerns were about optional inputs.

**Comment by jessesuen** [comment]
Fixed in: https://github.com/argoproj/argo/pull/1277
