### ISSUE TITLE
why need admin role ? What permissions does Argoexec need?

### ISSUE THREAD

**Issue by fudali113** [argoproj/argo#938]
**Is this a BUG REPORT or FEATURE REQUEST?**:
QUESTION

![image](https://user-images.githubusercontent.com/16189465/43822741-955996f8-9b1f-11e8-8bbf-6e53a6f154cb.png)

Can I not use the clusterrole if my tasks are all running in the same namespace?
 i not use resource type template；

**Comment by andreimc** [comment]
You can, refer to this issue: https://github.com/argoproj/argo/issues/932

I use a role as opposed to a cluster role, you just need to put namespace: in the argo configmap

**Comment by jessesuen** [comment]
Theres two roles to discuss:

1. workflow-controller - this can be an admin or clusteradmin depending if you want the controller to manage workflows across namespaces or not. There shouldn't be any need to change the actual privileges inside what's defined here: https://github.com/argoproj/argo/blob/master/install/manifests/02b_workflow-controller-cluster-role.yaml

2. the pods as part of the workflow - this is different depending on what you want the workflow to do. This will be different for everyone. For example, a workflow may or may not need to access secrets/volumes, or create custom resource instances. The getting started document has you using admin role, because most of the examples need additional privileges.

If you're looking to strip down the role of a workflow pod, know that at the very least, the argoexec sidecar which is added to each workflow pod, needs to annotate itself to communicate the output parameters/artifacts, error messages, script result. So it should have update/patch permissions to pods in its namespace.

**Comment by jessesuen** [comment]
BTW, I'll be getting to updating docs (long overdue) as we get closer to v2.2.

**Comment by jessesuen** [comment]
Closing answered question
