### ISSUE TITLE
Rename "s3" in Argo resource manifest schema. 

### ISSUE THREAD

**Issue by vicaire** [argoproj/argo#959]
FEATURE REQUEST:

When using artifacts, it seems that the manifest schema requires the string "s3" regardless of whether the bucket is in "s3", "minio", or "GCS". 

This has been confusing to some users. 

Would it be possible to rename this field in the schema? 

Example: 

data:
  config: |
    artifactRepository:
      s3:
        bucket: my-bucket
        endpoint: argo-artifacts-minio.default:9000
        insecure: true
        # accessKeySecret and secretKeySecret are secret selectors.
        # It references the k8s secret named 'argo-artifacts-minio'
        # which was created during the minio helm install. The keys,
        # 'accesskey' and 'secretkey', inside that secret are where the
        # actual minio credentials are stored.
        accessKeySecret:
          name: argo-artifacts-minio
          key: accesskey
        secretKeySecret:
          name: argo-artifacts-minio
          key: secretkey

**Comment by jessesuen** [comment]
@vicaire I don't think it's a good idea to rename the terminology away from `s3`. S3 has really become a protocol/API, not just a product from AWS. All the concepts and terminology (buckets, keys, accessKey, secretKey, signed urls, etc...) are, for a lack of a better word, "S3" concepts, So it's accurate to say that minio is a S3-compliant object store. Just as it is accurate to say that GCS (with interoperability mode turned on), is an S3-compliant object store. 

Another way to look at it, it's very possible that someday we would support GCS using Google's GCS native APIs (with interoperability mode turned *off*), which at that point, we would want to introduce a `gcs:` field, which would be distinctly different since it uses GCS APIs/protocol instead of S3 APIs. Just like the PR to introduce azure blob storage: https://github.com/argoproj/argo/pull/874.

**Comment by jessesuen** [comment]
Closing wontfix
